In [23]:
import numpy as np
import pandas as pd

df = pd.DataFrame(pd.read_csv("shark_attacks.csv"))

df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [25]:
df = df.drop(columns = ['Date', 'Year', 'Type', 'Activity',
       'Name', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'])

In [26]:
df.columns = df.columns.str.lower()

In [27]:
df.head()

         country              state                          location sex
0            USA         California  Big River Beach Mendocino County   M
1      Australia  Western Australia                           Exmouth   F
2      Australia  Western Australia                           Exmouth   M
3      Australia         Queensland               Lady Elliott Island  M
4  New Caledonia             Noumea       Anse Vata near Point Magnin   M

In [154]:
df.shape

(7082, 2)

In [227]:
df.isnull().sum()

date         0
year         0
full_date    0
dtype: int64

In [168]:
df.dtypes

date        str
year    float64
dtype: object

In [10]:
df["year"] = df["year"].fillna(0.0)

In [11]:
df["year"] = df["year"].apply(lambda year: str(int(year)))

In [12]:
df["full_date"] = df["date"] + " " +df["year"]

In [208]:
df.dtypes

date         str
year         str
full_date    str
dtype: object

In [13]:
df["full_date"] = df["full_date"].str.replace("-", " ", regex = False)

In [14]:
df["full_date"] = df["full_date"].str.replace("st|nd|rd|th|Before|Reported|reported", "", regex = True)

In [15]:
def remove_str(string):
    split = string.split()
    if len(split) >= 4:
        split = string.split()
        new_string = split[0] + " " + split[1] + " " + split[2]
        return new_string
    else: 
        return string

In [16]:
df["full_date"] = df["full_date"].apply(remove_str)

In [326]:
print(repr(df["full_date"][7000]))

'No date, May'

In [299]:
#df["final_date"] = pd.to_datetime(df["full_date"],format = "%d %B %Y", errors = "coerce")

In [17]:
format1 = pd.to_datetime(df["full_date"], format="%d %B %Y", errors="coerce")
format2 = pd.to_datetime(df["full_date"], format="%Y %m %d", errors="coerce")
format3 = pd.to_datetime(df["full_date"], format="%d %b %Y", errors="coerce")
df["final_date"] = format1.fillna(format2).fillna(format3)

In [18]:
df["final_date"].unique()

<DatetimeArray>
['2026-03-18 00:00:00', '2026-03-14 00:00:00', '2026-03-10 00:00:00',
 '2026-03-05 00:00:00', '2026-02-22 00:00:00', '2026-02-06 00:00:00',
 '2026-01-29 00:00:00', '2026-01-24 00:00:00', '2026-01-20 00:00:00',
 '2026-01-19 00:00:00',
 ...
 '1751-07-27 00:00:00', '1742-12-17 00:00:00', '1738-04-06 00:00:00',
 '1703-03-26 00:00:00', '1640-08-15 00:00:00', '1912-06-08 00:00:00',
 '1959-06-19 00:00:00', '1959-04-24 00:00:00', '1916-07-17 00:00:00',
 '1913-07-19 00:00:00']
Length: 5351, dtype: datetime64[us]

In [28]:
df["sex"].value_counts()

# I'm going to standarize the typing mistakes. But I'm discarding the rest because the sample is little

sex
M        5678
F         810
M           5
?           2
F           2
N           2
 M          1
m           1
lli         1
M x 2       1
.           1
Name: count, dtype: int64

In [44]:
df["sex"].isnull().sum()

np.int64(578)

In [29]:
sex_mapping = { "M" : "M",
                "F" : "F",
                "M " : "M",
                "F " : "F",
                " M" : "M",
                "m" : "M",
}

df["sex"] = df["sex"].map(sex_mapping)

In [30]:
print (df["sex"].value_counts())
print ("null values: ", df["sex"].isnull().sum())

sex
M    5685
F     812
Name: count, dtype: int64
null values:  585

In [63]:
df.dropna (subset = ["country", "state", "location"], thresh = 3).shape

(6274, 4)

In [66]:
df.dropna (subset = ["country", "state", "location"], thresh = 3).isna().sum()

country       0
state         0
location      0
sex         481
dtype: int64

In [64]:
df.dropna (subset = ["country", "state", "location"], thresh = 2).shape
# 600 were there is only one value missing of these three columns

(6815, 4)

In [65]:
df.dropna (subset = ["country", "state", "location"], thresh = 2).isna().sum()

country       5
state       230
location    306
sex         556
dtype: int64

In [61]:
df.dropna (subset = ["state", "location"], thresh = 2).shape

(6279, 4)

In [122]:
df["country"].value_counts().head()

country
USA             2580
AUSTRALIA       1482
SOUTH AFRICA     597
NEW ZEALAND      144
BAHAMAS          136
Name: count, dtype: int64

In [105]:
for country in df["country"].unique():
    print (country)

USA
Australia
New Caledonia
Cayman Islands
Brazil
US Virgin Islands
Mozambique
French Polynesia
Samoa
Columbia
Costa Rica
Bahamas
Puerto Rico
Spain
Canary Islands
South Africa
Vanuatu
Jamaica
Israel
Mexico
Maldives
Philippines
Turks and Caicos
Egypt
Thailand
New Zealand
Hawaii
Honduras
Indonesia
Morocco
Belize
Maldive Islands
Tobago
AUSTRALIA
INDIA
TRINIDAD
BAHAMAS
SOUTH AFRICA
MEXICO
NEW ZEALAND
EGYPT
BELIZE
PHILIPPINES
Coral Sea
SPAIN
PORTUGAL
SAMOA
COLOMBIA
ECUADOR
FRENCH POLYNESIA
NEW CALEDONIA
TURKS and CaICOS
CUBA
BRAZIL
SEYCHELLES
ARGENTINA
FIJI
MeXICO
ENGLAND
JAPAN
INDONESIA
JAMAICA
MALDIVES
THAILAND
COLUMBIA
COSTA RICA
British Overseas Territory
CANADA
JORDAN
ST KITTS / NEVIS
ST MARTIN
PAPUA NEW GUINEA
REUNION ISLAND
ISRAEL
CHINA
IRELAND
ITALY
MALAYSIA
LIBYA
nan
MAURITIUS
SOLOMON ISLANDS
ST HELENA, British overseas territory
COMOROS
REUNION
UNITED KINGDOM
UNITED ARAB EMIRATES
CAPE VERDE
Fiji
DOMINICAN REPUBLIC
CAYMAN ISLANDS
ARUBA
MOZAMBIQUE
PUERTO RICO
ATLANTIC OCEAN
GREECE
ST. MARTIN
FRANCE
TRINIDAD & TOBAGO
KIRIBATI
DIEGO GARCIA
TAIWAN
PALESTINIAN TERRITORIES
GUAM
NIGERIA
TONGA
SCOTLAND
CROATIA
SAUDI ARABIA
CHILE
ANTIGUA
KENYA
RUSSIA
TURKS & CAICOS
UNITED ARAB EMIRATES (UAE)
AZORES
SOUTH KOREA
MALTA
VIETNAM
MADAGASCAR
PANAMA
SOMALIA
NEVIS
BRITISH VIRGIN ISLANDS
NORWAY
SENEGAL
YEMEN
GULF OF ADEN
Sierra Leone
ST. MAARTIN
GRAND CAYMAN
Seychelles
LIBERIA
VANUATU
MEXICO
HONDURAS
VENEZUELA
SRI LANKA
 TONGA
URUGUAY
MICRONESIA
CARIBBEAN SEA
OKINAWA
TANZANIA
MARSHALL ISLANDS
EGYPT / ISRAEL
NORTHERN ARABIAN SEA
HONG KONG
EL SALVADOR
ANGOLA
BERMUDA
MONTENEGRO
IRAN
TUNISIA
NAMIBIA
NORTH ATLANTIC OCEAN
SOUTH CHINA SEA
BANGLADESH
PALAU
WESTERN SAMOA
PACIFIC OCEAN
BRITISH ISLES
GRENADA
IRAQ
TURKEY
SINGAPORE
NEW BRITAIN
SUDAN
JOHNSTON ISLAND
SOUTH PACIFIC OCEAN
NEW GUINEA
RED SEA
NORTH PACIFIC OCEAN
FEDERATED STATES OF MICRONESIA
MID ATLANTIC OCEAN
ADMIRALTY ISLANDS
BRITISH WEST INDIES
SOUTH ATLANTIC OCEAN
PERSIAN GULF
RED SEA / INDIAN OCEAN
PACIFIC OCEAN
NORTH SEA
NICARAGUA
MALDIVE ISLANDS
AMERICAN SAMOA
ANDAMAN / NICOBAR ISLANDAS
GABON
MAYOTTE
NORTH ATLANTIC OCEAN
THE BALKANS
SUDAN?
MARTINIQUE
INDIAN OCEAN
GUATEMALA
NETHERLANDS ANTILLES
NORTHERN MARIANA ISLANDS
IRAN / IRAQ
JAVA
SIERRA LEONE
 PHILIPPINES
NICARAGUA
CENTRAL PACIFIC
SOLOMON ISLANDS / VANUATU
SOUTHWEST PACIFIC OCEAN
BAY OF BENGAL
MID-PACIFC OCEAN
SLOVENIA
CURACAO
ICELAND
ITALY / CROATIA
BARBADOS
MONACO
GUYANA
HAITI
SAN DOMINGO
KUWAIT
YEMEN
FALKLAND ISLANDS
CRETE
CYPRUS
EGYPT
WEST INDIES
BURMA
LEBANON
PARAGUAY
BRITISH NEW GUINEA
CEYLON
OCEAN
GEORGIA
SYRIA
TUVALU
INDIAN OCEAN?
GUINEA
ANDAMAN ISLANDS
EQUATORIAL GUINEA / CAMEROON
COOK ISLANDS
TOBAGO
PERU
AFRICA
ALGERIA
Coast of AFRICA
TASMAN SEA
GHANA
GREENLAND
MEDITERRANEAN SEA
SWEDEN
ROATAN
Between PORTUGAL & INDIA
DJIBOUTI
BAHREIN
KOREA
RED SEA?
ASIA?
CEYLON (SRI LANKA)

In [31]:
def lowletters(word):
    str_word =str(word)
    return str_word.lower().replace("?", "").strip()

In [32]:
df["country"] = df["country"].apply(lowletters)
df["country"].value_counts().head(20)

country
usa                 2580
australia           1526
south africa         599
new zealand          146
bahamas              141
papua new guinea     136
brazil               123
mexico               107
italy                 72
fiji                  70
new caledonia         68
philippines           65
reunion               60
egypt                 53
mozambique            52
nan                   50
cuba                  49
spain                 47
india                 41
french polynesia      40
Name: count, dtype: int64

In [33]:
df["state"] = df["state"].apply(lowletters)
df["state"].value_counts().head(20)

state
florida                  1193
new south wales           523
nan                       487
queensland                355
hawaii                    345
california                328
western australia         244
kwazulu-natal             219
western cape province     197
south carolina            176
eastern cape province     168
north carolina            122
south australia           120
victoria                   98
texas                      83
pernambuco                 80
north island               76
torres strait              72
new jersey                 57
new york                   48
Name: count, dtype: int64

In [34]:
df["location"] = df["location"].apply(lowletters)
df["location"].value_counts().head(20)

location
nan                                              567
new smyrna beach, volusia county                 193
daytona beach, volusia county                     34
ponce inlet, volusia county                       28
myrtle beach, horry county                        22
melbourne beach, brevard county                   21
cocoa beach, brevard  county                      19
durban                                            18
isle of palms, charleston county                  16
piedade                                           14
boa viagem, recife                                14
cocoa beach, brevard county                       13
jensen beach, martin county                       13
jacksonville beach, duval county                  13
juno beach, palm beach county                     12
ponce inlet, new smyrna beach, volusia county     12
ormond beach, volusia county                      11
palm beach, palm beach county                     11
mossel bay                                        11
ahvaz, on the karun river                         11
Name: count, dtype: int64

In [78]:
df.duplicated().sum()

# I wouldn't remove them because maybe they are the same row but different days, what would meake sense for places and sex with a lot of accidents

np.int64(1705)

In [35]:
df.head()

         country              state                          location sex
0            usa         california  big river beach mendocino county   M
1      australia  western australia                           exmouth   F
2      australia  western australia                           exmouth   M
3      australia         queensland               lady elliott island   M
4  new caledonia             noumea       anse vata near point magnin   M

In [36]:
csls_df = df

In [37]:
csls_df.head()

         country              state                          location sex
0            usa         california  big river beach mendocino county   M
1      australia  western australia                           exmouth   F
2      australia  western australia                           exmouth   M
3      australia         queensland               lady elliott island   M
4  new caledonia             noumea       anse vata near point magnin   M

In [22]:
time_df = df [["final_date"]]
time_df.nunique()

final_date    5350
dtype: int64

In [39]:
time_df["country"] = df["country"]

In [40]:
time_df["state"] = df["state"]

In [41]:
time_df["location"] = df["location"]

In [42]:
time_df["sex"] = df["sex"]

In [43]:
time_df.head()

,final_date,country,state,location,sex
0,2026-03-18,usa,california,big river beach mendocino county,M
1,2026-03-14,australia,western australia,exmouth,F
2,2026-03-10,australia,western australia,exmouth,M
3,2026-03-05,australia,queensland,lady elliott island,M
4,2026-02-22,new caledonia,noumea,anse vata near point magnin,M

In [44]:
time_df.to_csv("./clean_jorge.csv", index = False)

In [45]:
import pandas as pd
df_new = pd.read_csv("./clean_jorge.csv")

In [46]:
df_new.head()

,final_date,country,state,location,sex
0,2026-03-18,usa,california,big river beach mendocino county,M
1,2026-03-14,australia,western australia,exmouth,F
2,2026-03-10,australia,western australia,exmouth,M
3,2026-03-05,australia,queensland,lady elliott island,M
4,2026-02-22,new caledonia,noumea,anse vata near point magnin,M

In [351]:
df_new = df_new[['date', 'country', 'state', 'location', 'sex']]